language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t amitweiss/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true amitweiss/docker-react npm run test -- --coverage

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "docker-react"
#   env: "Docker-react-env"
#   bucket_name: "<Created automatically by elasticbeanstalk>"
#   bucket_path: "docker-react"
#   on:
#     branch: master # only deploy from master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: 
#     secure: $AWS_SECRET_KEY # Stored as env variable in TravisCI



